# Generated by Django 2.2.3 on 2019-07-14 14:52

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bride', models.CharField(blank=True, max_length=200)),
                ('bridefullname', models.CharField(blank=True, max_length=200)),
                ('groom', models.CharField(blank=True, max_length=200)),
                ('groomfullname', models.CharField(blank=True, max_length=200)),
                ('addressline1', models.CharField(blank=True, max_length=200)),
                ('addressline2', models.CharField(blank=True, max_length=200)),
                ('addressline3', models.CharField(blank=True, max_length=200)),
                ('postalcode', models.CharField(blank=True, max_length=200)),
                ('host1', models.CharField(blank=True, max_length=200)),
                ('host2', models.CharField(blank=True, max_length=200)),
                ('host3', models.CharField(blank=True, max_length=200)),
                ('host4', models.CharField(blank=True, max_length=200)),
                ('bridecontactname', models.CharField(blank=True, max_length=200)),
                ('bridecontactname2', models.CharField(blank=True, max_length=200)),
                ('bridecontactno', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('bridecontactno2', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('groomcontactname', models.CharField(blank=True, max_length=200)),
                ('groomcontactname2', models.CharField(blank=True, max_length=200)),
                ('groomcontactno', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('groomcontactno2', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('eventdatetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('no_of_guests_attending', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2000)])),
                ('customeremail', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('bridecontact_number', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('groomcontact_number', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('eventstarttime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('eventendtime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'customerdetails',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Group',
            },
        ),
        migrations.CreateModel(
            name='itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('endtime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'itinerary',
            },
        ),
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
            options={
                'verbose_name_plural': 'RSVP',
            },
        ),
        migrations.CreateModel(
            name='wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('created_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Wish',
            },
        ),
        migrations.CreateModel(
            name='Guestbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('no_of_guests_invited', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('no_of_guests_attending', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('email', models.EmailField(blank=True, max_length=70, null=True, unique=True)),
                ('contact_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvitesapp.Group')),
                ('rsvp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mvitesapp.Rsvp')),
            ],
            options={
                'verbose_name_plural': 'Guestbook',
            },
        ),
    ]
