# Generated by Django 2.2.3 on 2019-07-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvitesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
